apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: {}
  name:  myapp
  namespace: labs
  labels:
    app:  myapp
spec:
  selector:
    matchLabels:
      app: myapp
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        # vault sidecar injection
        vault.hashicorp.com/agent-inject: "true"
        # vault.hashicorp.com/agent-inject-status: "update"
        vault.hashicorp.com/role: "demo"
        vault.hashicorp.com/agent-inject-secret-config.ini: "kv/demo"
        vault.hashicorp.com/agent-inject-template-config.ini: |
          [DEFAULT]
          LogLevel = DEBUG

          [DATABASE]
          {{- with secret "kv/demo" -}}
          Address={{ .Data.plop }}
          {{- end }}
          Port=3306

      labels:
        app:  myapp
    spec:
      containers:
      - name:  myapp
        image:  jweissig/app:0.0.1
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        # livenessProbe:
        #   tcpSocket:
        #     port: 80
        #   initialDelaySeconds: 5
        #   timeoutSeconds: 5
        #   successThreshold: 1
        #   failureThreshold: 3
        #   periodSeconds: 10
        # readinessProbe:
        #   httpGet:
        #     path: /
        #     port: 80
        #   initialDelaySeconds: 5
        #   timeoutSeconds: 2
        #   successThreshold: 1
        #   failureThreshold: 3
        #   periodSeconds: 10
        ports:
        - containerPort:  80
          name:  myapp
      restartPolicy: Always
